name: update manifest
on:
  pull_request:
    types:
      - closed
    branches:
      - master
    paths:
      - 'docs/shipping/**'

jobs:
  update_manifest_content:
    if: ${{ github.event.pull_request.merged == true }}
    name: update manifest content
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python3 _manifest/manifest_generator.py
      - uses: EndBug/add-and-commit@v9
        with:
          add: './data/manifest.json'
          default_author: github_actions
